name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip python3-dev build-essential \
            libffi-dev libssl-dev zlib1g-dev \
            libjpeg-dev libpng-dev libfreetype6-dev \
            openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: buildozer android debug

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: BearGoesRacing.apk
          path: bin/*.apk
